-- ============================================================
-- DDL SCRIPTS - METADATA INTELLIGENCE PLATFORM
-- Generated for simulation purposes
-- ============================================================

-- SCHEMA: CORE_BANKING
-- TABLE: XXX_HESAP
CREATE TABLE CORE_BANKING.XXX_HESAP (
    HESAP_NO        VARCHAR2(26)    NOT NULL,
    MUSTERI_NO      NUMBER(10)      NOT NULL,
    ACILIS_TARIHI   DATE            NOT NULL,
    VALOR_TARIHI    DATE,
    HESAP_TIP_KOD   NUMBER(2)       NOT NULL,
    HESAP_DURUM_KOD NUMBER(1)       NOT NULL,
    SUBE_KOD        NUMBER(4)       NOT NULL,
    CONSTRAINT PK_XXX_HESAP PRIMARY KEY (HESAP_NO),
    CONSTRAINT FK_HESAP_MUSTERI FOREIGN KEY (MUSTERI_NO)
        REFERENCES CORE_BANKING.XXX_MUSTERI(MUSTERI_NO),
    CONSTRAINT FK_HESAP_TIP FOREIGN KEY (HESAP_TIP_KOD)
        REFERENCES CORE_BANKING.LKP_HESAP_TIP(KOD)
    -- NOTE: HESAP_DURUM_KOD has no FK to LKP table — missing lookup
    -- NOTE: SUBE_KOD references LKP_SUBE but FK not defined in model
);

-- TABLE: LKP_HESAP_TIP
CREATE TABLE CORE_BANKING.LKP_HESAP_TIP (
    KOD         NUMBER(2)       NOT NULL,
    ACIKLAMA    VARCHAR2(100)   NOT NULL,
    CONSTRAINT PK_LKP_HESAP_TIP PRIMARY KEY (KOD)
);

INSERT INTO CORE_BANKING.LKP_HESAP_TIP VALUES (1, 'Vadesiz');
INSERT INTO CORE_BANKING.LKP_HESAP_TIP VALUES (2, 'Vadeli');
INSERT INTO CORE_BANKING.LKP_HESAP_TIP VALUES (3, 'Döviz');
INSERT INTO CORE_BANKING.LKP_HESAP_TIP VALUES (4, 'Altın');
INSERT INTO CORE_BANKING.LKP_HESAP_TIP VALUES (5, 'Yatırım');

-- ============================================================
-- SCHEMA: CREDIT
-- TABLE: KRD_MUS_KREDI (PARTITIONED)
CREATE TABLE CREDIT.KRD_MUS_KREDI (
    KRD_NO              VARCHAR2(20)    NOT NULL,
    MUSTERI_NO          NUMBER(10)      NOT NULL,
    KRD_TUTAR           NUMBER(15,2)    NOT NULL,
    KRD_MUS_KOBI_TIP    NUMBER(1),
    INT_SHK_A_30GCK_ADT_LM NUMBER(15,2),
    KRD_DURUM           NUMBER(1)       NOT NULL,
    ISLEM_TARIHI        DATE            NOT NULL,
    CONSTRAINT PK_KRD_MUS_KREDI PRIMARY KEY (KRD_NO, ISLEM_TARIHI)
)
PARTITION BY RANGE (ISLEM_TARIHI) (
    PARTITION P_2023 VALUES LESS THAN (TO_DATE('2024-01-01','YYYY-MM-DD')),
    PARTITION P_2024 VALUES LESS THAN (TO_DATE('2025-01-01','YYYY-MM-DD')),
    PARTITION P_2025 VALUES LESS THAN (TO_DATE('2026-01-01','YYYY-MM-DD')),
    PARTITION P_MAX  VALUES LESS THAN (MAXVALUE)
);
-- NOTE: KRD_MUS_KOBI_TIP has no LKP table
-- NOTE: KRD_DURUM has no LKP table; documented values: 0,1,2 but 3 may exist

-- ============================================================
-- SCHEMA: CRM
-- TABLE: MUS_SEGMENTASYON
-- NOTE: DDL not available for this table
-- ============================================================

-- SCHEMA: RISK
-- TABLE: RISK_IZLEME (PARTITIONED)
CREATE TABLE RISK.RISK_IZLEME (
    MUSTERI_NO      NUMBER(10)      NOT NULL,
    RAPOR_TARIHI    DATE            NOT NULL,
    RISK_SKOR       NUMBER(5,2),
    RISK_SINIF      VARCHAR2(10),
    CONSTRAINT PK_RISK_IZLEME PRIMARY KEY (MUSTERI_NO, RAPOR_TARIHI)
)
PARTITION BY RANGE (RAPOR_TARIHI) (
    PARTITION P_2023 VALUES LESS THAN (TO_DATE('2024-01-01','YYYY-MM-DD')),
    PARTITION P_2024 VALUES LESS THAN (TO_DATE('2025-01-01','YYYY-MM-DD')),
    PARTITION P_2025 VALUES LESS THAN (TO_DATE('2026-01-01','YYYY-MM-DD')),
    PARTITION P_MAX  VALUES LESS THAN (MAXVALUE)
);

-- TABLE: XXX_MUSTERI
CREATE TABLE CORE_BANKING.XXX_MUSTERI (
    MUSTERI_NO      NUMBER(10)      NOT NULL,
    MUST_TARIH      DATE,
    MUST_KOD        NUMBER(2),
    MUST_DURUM      NUMBER(1),
    CONSTRAINT PK_XXX_MUSTERI PRIMARY KEY (MUSTERI_NO)
);

-- TABLE: XXX_ISLEM (PARTITIONED)
CREATE TABLE CORE_BANKING.XXX_ISLEM (
    ISLM_NO         VARCHAR2(20)    NOT NULL,
    ISLM_TARIH      DATE            NOT NULL,
    ISLM_KOD        NUMBER(2),
    ISLM_DURUM      NUMBER(1),
    MUSTERI_NO      NUMBER(10)      NOT NULL,
    CONSTRAINT PK_XXX_ISLEM PRIMARY KEY (ISLM_NO, ISLM_TARIH)
)
PARTITION BY RANGE (ISLM_TARIH) (
    PARTITION P_MAX VALUES LESS THAN (MAXVALUE)
);

-- TABLE: KRD_TEMINAT
CREATE TABLE CREDIT.KRD_TEMINAT (
    TEM_NO          VARCHAR2(20)    NOT NULL,
    TEM_TARIH       DATE,
    TEM_KOD         NUMBER(2),
    TEM_DURUM       NUMBER(1),
    MUSTERI_NO      NUMBER(10),
    CONSTRAINT PK_KRD_TEMINAT PRIMARY KEY (TEM_NO)
);

-- TABLE: KRD_BASVURU
CREATE TABLE CREDIT.KRD_BASVURU (
    BASV_NO         VARCHAR2(20)    NOT NULL,
    BASV_TARIH      DATE,
    BASV_KOD        NUMBER(2),
    BASV_DURUM      NUMBER(1),
    MUSTERI_NO      NUMBER(10)      NOT NULL,
    CONSTRAINT PK_KRD_BASVURU PRIMARY KEY (BASV_NO)
);

-- TABLE: RISK_LIMIT
CREATE TABLE RISK.RISK_LIMIT (
    LIM_NO          VARCHAR2(20)    NOT NULL,
    LIM_TARIH       DATE,
    LIM_KOD         NUMBER(2),
    LIM_DURUM       NUMBER(1),
    MUSTERI_NO      NUMBER(10)      NOT NULL,
    CONSTRAINT PK_RISK_LIMIT PRIMARY KEY (LIM_NO)
);

-- TABLE: RISK_AML
CREATE TABLE RISK.RISK_AML (
    AML_NO          VARCHAR2(20)    NOT NULL,
    AML_TARIH       DATE,
    AML_KOD         NUMBER(2),
    AML_DURUM       NUMBER(1),
    MUSTERI_NO      NUMBER(10)      NOT NULL,
    CONSTRAINT PK_RISK_AML PRIMARY KEY (AML_NO)
);
